language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
cache: pip
install:
  - pip install -e .[dev]
  - pip install coverage
script:
  - coverage run --source ./rohdeschwarz -m unittest discover
after_success:
  - coverage report
